live_config_reload = true

[shell]
program = "/opt/homebrew/bin/fish"

[colors]
draw_bold_text_with_bright_colors = true
cursor = { cursor = "#a277ff" }
selection = { background = "#555555" }

[colors.primary]
background = "#252525"
foreground = "#edecee"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow =  "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.search]
matches = { foreground = "#000000", background = "#ffffff" }
focused_match = { foreground = "#ffffff", background = "#9F7AF5" }

[font]
normal = { family = "SFMono Nerd Font", style = "Regular" }
bold = { family = "SFMono Nerd Font", style = "Bold" }
italic = { family = "SFMono Nerd Font", style = "Italic" }
bold_italic = { family = "SFMono Nerd Font", style = "Italic" }
size = 16.0
offset = { x = 0, y = 9 }
glyph_offset = { x = 0, y = 3 }

[window]
padding = { x = 8, y = 0 }
dynamic_padding = true
decorations = "Buttonless"
dimensions = { columns = 106, lines = 25 }

[scrolling]
history = 100000
multiplier = 4

[cursor]
style = { shape = "Beam" }

[selection]
semantic_escape_chars = ",│`|:\"'' ()[]{}<>"
save_to_clipboard = true

[keyboard]
bindings = [
]
